# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wfs_DERA
                                 A QGIS plugin
 Carga de los servicios Wfs de los Datos Espaciales de Referencia DERA  
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-07
        copyright            : (C) 2023 by Manuel Cano
        email                : mcanop29@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Wfs_DERA class from file Wfs_DERA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wfs_from_dera import Wfs_DERA
    return Wfs_DERA(iface)
