# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wfs_DERADialog
                                 A QGIS plugin
 Carga de los servicios Wfs de los Datos Espaciales de Referencia DERA  
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-07
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Manuel Cano
        email                : mcanop29@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

try:
    from qgis.core import Qgis
    from PyQt5.QtCore import *
    from PyQt5.QtGui import *
    from PyQt5.QtWidgets import *
    from PyQt5 import uic

    QT_VERSION = 5
    os.environ['QT_API'] = 'pyqt5'
except:
    from PyQt4.QtCore import *
    from PyQt4.QtGui import *
    from PyQt4 import uic

    QT_VERSION = 4

import os.path
from qgis.core import *
from qgis.gui import *

from .resources import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wfs_from_dera_dialog_base.ui'))


#class Wfs_DERADialog(QtWidgets.QDialog, FORM_CLASS):
class wfsfromderadialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(wfsfromderadialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.checkBox_wms.setEnabled(False)
        self.checkBox_wfs.setEnabled(False)

    def act_wms_wfs(self):
        self.checkBox_wms.setEnabled(True)
        self.checkBox_wfs.setEnabled(True)

    def des_wms_wfs(self):
        self.checkBox_wms.setEnabled(False)
        self.checkBox_wfs.setEnabled(False)

